Add ECKeypair doc for :model module
komputing/KEthereum pull request #155
Opened 2023-10-08 13:55 UTC by bigman212

I've decided to help and write some documentation on how to use this lib. 
I haven't done much here - just I want to make sure that this is what you want.

2023-10-08 13:57 UTC, bigman212 commented on wallet/src/main/kotlin/org/kethereum/wallet/WalletFile.kt
> +    password: String,
sorry, but these indents were something else :)

2023-10-08 13:57 UTC, bigman212 commented on wallet/src/test/kotlin/org/kethereum/wallet/WalletTest.kt
> +        val walletFile = loadWalletFile(SCRYPT_TEST_JSON)
all unit tests are green, just a small variable extraction to make it more readable

2023-10-08 15:22 UTC, ligi requested changes
Thanks! Just minor nits

2023-10-08 15:22 UTC, ligi commented on model/README.md
> +implementation("com.github.walleth.kethereum:model:$KETHEREUM_VERSION")
```suggestion
implementation("com.github.komputing.kethereum:model:$KETHEREUM_VERSION")
```

2023-10-08 15:25 UTC, bigman212 commented on model/README.md
> +implementation("com.github.walleth.kethereum:model:$KETHEREUM_VERSION")
good one, thanks!

2023-10-08 15:25 UTC, bigman212 commented
@ligi feel free to merge.

2023-10-13 21:31 UTC, ligi approved these changes

2023-10-13 21:31 UTC, merged